const $=id=>document.getElementById(id);
const video=$("camera"),stage=$("stage"),overlay=$("overlayCanvas"),cal=$("calibrationCanvas");
const input=$("imageInput"),startBtn=$("startBtn"),lockBtn=$("lockBtn"),unlockBtn=$("unlockBtn");
const opacity=$("opacity"),opacityOut=$("opacityOut"),statusEl=$("status"),hint=$("stageHint"),lockBadge=$("canvasLock"),tracking=$("trackingStatus");
let stream=null,reference=null,corners=[],locked=false,trackingOn=false,prevGray=null,prevPts=null,lastTrack=0,animationId=null;
const refCanvas=document.createElement("canvas");
const overlayCtx=overlay.getContext("2d");

input.addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;reference=new Image();reference.onload=()=>{refCanvas.width=reference.naturalWidth;refCanvas.height=reference.naturalHeight;refCanvas.getContext("2d").drawImage(reference,0,0);$("setup").classList.add("hidden");stage.classList.remove("hidden");statusEl.textContent="Start the camera, then tap the 4 corners of your canvas.";resizeCanvases()};reference.src=URL.createObjectURL(f)});
startBtn.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();resizeCanvases();startBtn.textContent="Camera on";startBtn.disabled=true;statusEl.textContent="Tap the 4 corners of your physical canvas, clockwise.";hint.textContent="Tap the 4 canvas corners, clockwise"}catch(e){alert("Camera access was blocked. Allow Camera for this site in Safari.")}};
function resizeCanvases(){const r=stage.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);[overlay,cal].forEach(c=>{c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.style.width=r.width+"px";c.style.height=r.height+"px"});drawCalibration();if(locked)renderReference()}
window.addEventListener("resize",()=>{if(!locked)resizeCanvases()});
function drawCalibration(){const ctx=cal.getContext("2d"),d=Math.min(devicePixelRatio||1,2);ctx.clearRect(0,0,cal.width,cal.height);ctx.save();ctx.scale(d,d);corners.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#111";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(i+1),p.x,p.y)});if(corners.length>1){ctx.beginPath();ctx.moveTo(corners[0].x,corners[0].y);corners.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));if(corners.length===4)ctx.closePath();ctx.strokeStyle="rgba(255,255,255,.9)";ctx.lineWidth=2;ctx.stroke()}ctx.restore()}
cal.addEventListener("pointerdown",e=>{if(locked||!reference||!stream||corners.length>=4)return;const r=cal.getBoundingClientRect();corners.push({x:e.clientX-r.left,y:e.clientY-r.top});drawCalibration();if(corners.length===4){lockBtn.disabled=false;statusEl.textContent="Canvas calibrated. Tap Lock canvas.";hint.textContent="4 corners set — tap Lock canvas"}});
opacity.oninput=()=>{opacityOut.textContent=opacity.value+"%";if(locked)renderReference()};
function stageToVideo(p){const vw=video.videoWidth||1280,vh=video.videoHeight||720,sw=stage.clientWidth,sh=stage.clientHeight,s=Math.max(sw/vw,sh/vh),dw=vw*s,dh=vh*s,ox=(sw-dw)/2,oy=(sh-dh)/2;return{x:(p.x-ox)/s,y:(p.y-oy)/s}}
function videoToStage(p){const vw=video.videoWidth||1280,vh=video.videoHeight||720,sw=stage.clientWidth,sh=stage.clientHeight,s=Math.max(sw/vw,sh/vh),dw=vw*s,dh=vh*s,ox=(sw-dw)/2,oy=(sh-dh)/2;return{x:p.x*s+ox,y:p.y*s+oy}}
function renderReference(){if(!reference||corners.length!==4||!window.cv||!cv.Mat)return;try{overlayCtx.clearRect(0,0,overlay.width,overlay.height);const d=Math.min(devicePixelRatio||1,2),W=overlay.width/d,H=overlay.height/d;const src=cv.imread(refCanvas),srcRGBA=new cv.Mat();cv.cvtColor(src,srcRGBA,cv.COLOR_RGB2RGBA);src.delete();const srcPts=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,refCanvas.width,0,refCanvas.width,refCanvas.height,0,refCanvas.height]);const dst=corners.flatMap(p=>[p.x*d,p.y*d]);const dstPts=cv.matFromArray(4,1,cv.CV_32FC2,dst);const M=cv.getPerspectiveTransform(srcPts,dstPts);const out=new cv.Mat(overlay.height,overlay.width,cv.CV_8UC4,new cv.Scalar(0,0,0,0));cv.warpPerspective(srcRGBA,out,M,new cv.Size(overlay.width,overlay.height),cv.INTER_LINEAR,cv.BORDER_CONSTANT,new cv.Scalar(0,0,0,0));const temp=document.createElement("canvas");temp.width=overlay.width;temp.height=overlay.height;cv.imshow(temp,out);overlayCtx.globalAlpha=Number(opacity.value)/100;overlayCtx.drawImage(temp,0,0);overlayCtx.globalAlpha=1;srcRGBA.delete();srcPts.delete();dstPts.delete();M.delete();out.delete()}catch(e){statusEl.textContent="Reference render error: "+e.message}}
lockBtn.onclick=()=>{if(corners.length!==4)return;if(!window.cv||!cv.Mat){statusEl.textContent="Loading the tracing engine… wait a moment, then tap Lock canvas again.";return}locked=true;lockBtn.classList.add("hidden");unlockBtn.classList.remove("hidden");cal.classList.add("hidden");lockBadge.classList.remove("hidden");tracking.classList.remove("hidden");statusEl.textContent="Canvas locked. Reference is visible and mapped to the canvas.";hint.textContent="Move slowly — canvas locked";renderReference();startTracking()};
unlockBtn.onclick=()=>unlock(false);$("resetBtn").onclick=()=>unlock(true);function unlock(reset){locked=false;trackingOn=false;if(animationId)cancelAnimationFrame(animationId);animationId=null;unlockBtn.classList.add("hidden");lockBtn.classList.remove("hidden");lockBtn.disabled=reset;lockBadge.classList.add("hidden");tracking.classList.add("hidden");prevGray?.delete?.();prevPts?.delete?.();prevGray=null;prevPts=null;overlayCtx.clearRect(0,0,overlay.width,overlay.height);if(reset){corners=[];drawCalibration();statusEl.textContent="Reset. Start again by tapping the 4 canvas corners.";hint.textContent="Tap the 4 canvas corners, clockwise"}else{drawCalibration();statusEl.textContent="Canvas unlocked. Recalibrate if needed.";hint.textContent="Tap the 4 canvas corners, clockwise"}}
$("gridBtn").onclick=()=>stage.classList.toggle("grid-on");
function startTracking(){trackingOn=true;prevGray?.delete?.();prevPts?.delete?.();prevGray=new cv.Mat();const cap=new cv.VideoCapture(video),src=new cv.Mat(video.videoHeight,video.videoWidth,cv.CV_8UC4);cap.read(src);cv.cvtColor(src,prevGray,cv.COLOR_RGBA2GRAY);const pts=corners.map(stageToVideo).flatMap(p=>[p.x,p.y]);prevPts=cv.matFromArray(4,1,cv.CV_32FC2,pts);src.delete();animationId=requestAnimationFrame(trackLoop)}
function trackLoop(t){if(!trackingOn||!locked)return;if(t-lastTrack<120){animationId=requestAnimationFrame(trackLoop);return}lastTrack=t;try{const cap=new cv.VideoCapture(video),frame=new cv.Mat(video.videoHeight,video.videoWidth,cv.CV_8UC4),gray=new cv.Mat();cap.read(frame);cv.cvtColor(frame,gray,cv.COLOR_RGBA2GRAY);const next=new cv.Mat(),st=new cv.Mat(),err=new cv.Mat();cv.calcOpticalFlowPyrLK(prevGray,gray,prevPts,next,st,err,new cv.Size(21,21),3,new cv.TermCriteria(cv.TERM_CRITERIA_EPS|cv.TERM_CRITERIA_COUNT,30,.01));let good=0;const pts=[];for(let i=0;i<4;i++){if(st.data[i]){pts.push({x:next.data32F[i*2],y:next.data32F[i*2+1]});good++}else pts.push(stageToVideo(corners[i]))}if(good>=3){corners=pts.map(videoToStage);renderReference();tracking.textContent=good===4?"● Tracking":"● Tracking (partial)"}else tracking.textContent="⚠ Tracking weak — hold phone steady";prevGray.delete();prevGray=gray.clone();prevPts.delete();prevPts=next.clone();frame.delete();gray.delete();next.delete();st.delete();err.delete()}catch(e){tracking.textContent="⚠ Tracking unavailable"}animationId=requestAnimationFrame(trackLoop)}